server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567
    url: jdbc:mysql://localhost:3306/mybatispdemo?characterEncoding=utf-8&&serverTimezone=UTC
